/**
 * Namf_EventExposure
 * AMF Event Exposure Service © 2019, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * SubscriptionsCollectionDocumentApiImplEventExposure.h
 *
 *
 */

#ifndef SUBSCRIPTIONS_COLLECTION_DOCUMENT_API_IMPL_EVENT_EXPOSURE_H_
#define SUBSCRIPTIONS_COLLECTION_DOCUMENT_API_IMPL_EVENT_EXPOSURE_H_

#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <SubscriptionsCollectionDocumentApiEventExposure.h>

#include <pistache/optional.h>

#include "AmfCreateEventSubscription.h"
#include "AmfCreatedEventSubscription.h"
#include "ProblemDetails.h"
#include "amf_app.hpp"

namespace oai::amf::api {

using namespace oai::amf::model;
using namespace oai::amf::api;

class SubscriptionsCollectionDocumentApiImplEventExposure
    : public SubscriptionsCollectionDocumentApiEventExposure {
 public:
  explicit SubscriptionsCollectionDocumentApiImplEventExposure(
      const std::shared_ptr<Pistache::Rest::Router>& rtr,
      amf_application::amf_app* amf_app_inst);
  ~SubscriptionsCollectionDocumentApiImplEventExposure() override = default;

  void create_subscription(
      const AmfCreateEventSubscription& amfCreateEventSubscription,
      Pistache::Http::ResponseWriter& response);

 private:
  amf_application::amf_app* m_amf_app;
};

}  // namespace oai::amf::api

#endif
