#/*
# * Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
# * contributor license agreements.  See the NOTICE file distributed with
# * this work for additional information regarding copyright ownership.
# * The OpenAirInterface Software Alliance licenses this file to You under
# * the OAI Public License, Version 1.1  (the "License"); you may not use this file
# * except in compliance with the License.
# * You may obtain a copy of the License at
# *
# *      http://www.openairinterface.org/?page_id=698
# *
# * Unless required by applicable law or agreed to in writing, software
# * distributed under the License is distributed on an "AS IS" BASIS,
# * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# * See the License for the specific language governing permissions and
# * limitations under the License.
# *-------------------------------------------------------------------------------
# * For more information about the OpenAirInterface (OAI) Software Alliance:
# *      contact@openairinterface.org
# */
#---------------------------------------------------------------------
#
# Dockerfile for the Open-Air-Interface AUSF service
#   Valid for Ubuntu-18.04 (bionic)
#
#---------------------------------------------------------------------

#---------------------------------------------------------------------
# BUILDER IMAGE
#---------------------------------------------------------------------
FROM oai-ausf-base:latest as oai-ausf-builder

WORKDIR /openair-ausf/
COPY . /openair-ausf
RUN cp -Rf /openair-ausf-ext-ref /openair-ausf/build/ext

# Building AUSF
WORKDIR /openair-ausf/build/scripts
RUN ./build_ausf --clean --Verbose --build-type Release --jobs && \
    mv /openair-ausf/build/ausf/build/ausf /openair-ausf/build/ausf/build/oai_ausf

#---------------------------------------------------------------------
# TARGET IMAGE
#---------------------------------------------------------------------
FROM ubuntu:bionic as oai-ausf
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Paris
# We install some debug tools for the moment in addition of mandatory libraries
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get upgrade --yes && \
    DEBIAN_FRONTEND=noninteractive apt-get install --yes \
      psmisc \
      net-tools \
      tzdata \
      bc \
      tshark \
      perl \
      libasan4 \
      libnettle6 \
      libnghttp2-14 \
      libhogweed4 \
      libldap-2.4-2 \
      librtmp1 \
      libpsl5 \
      libconfig++9v5 \
  && rm -rf /var/lib/apt/lists/*

# Copying executable and generated libraries
WORKDIR /openair-ausf/bin
COPY --from=oai-ausf-builder \
    /openair-ausf/build/ausf/build/oai_ausf \
    /openair-ausf/scripts/entrypoint.sh \
    ./

COPY --from=oai-ausf-builder \
    /usr/local/lib/libpistache.so \
    /usr/lib/libboost_system.so.1.67.0 \
    /usr/local/lib/libnghttp2_asio.so.1 \
    /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4 \
    /usr/local/lib/

RUN ldconfig

WORKDIR /openair-ausf/etc
COPY --from=oai-ausf-builder /openair-ausf/etc/ausf.conf .

WORKDIR /openair-ausf

EXPOSE 80/tcp

ENTRYPOINT ["/bin/bash","/openair-ausf/bin/entrypoint.sh"]
CMD ["/openair-ausf/bin/oai_ausf", "-c" , "/openair-ausf/etc/ausf.conf", "-o"]
