/**
 * NSSF NSSAI Availability
 * NSSF NSSAI Availability Service. © 2021, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * TaiRange.h
 *
 * Range of TAIs (Tracking Area Identities)
 */

#ifndef TaiRange_H_
#define TaiRange_H_

#include "PlmnId.h"
#include "TacRange.h"
#include <nlohmann/json.hpp>
#include <string>
#include <vector>

namespace oai {
namespace nssf_server {
namespace model {

/// <summary>
/// Range of TAIs (Tracking Area Identities)
/// </summary>
class TaiRange {
 public:
  TaiRange();
  virtual ~TaiRange() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const TaiRange& rhs) const;
  bool operator!=(const TaiRange& rhs) const;

  /////////////////////////////////////////////
  /// TaiRange members

  /// <summary>
  ///
  /// </summary>
  PlmnId getPlmnId() const;
  void setPlmnId(PlmnId const& value);
  /// <summary>
  ///
  /// </summary>
  std::vector<TacRange> getTacRangeList() const;
  void setTacRangeList(std::vector<TacRange> const& value);
  /// <summary>
  ///
  /// </summary>
  std::string getNid() const;
  void setNid(std::string const& value);
  bool nidIsSet() const;
  void unsetNid();

  friend void to_json(nlohmann::json& j, const TaiRange& o);
  friend void from_json(const nlohmann::json& j, TaiRange& o);

 protected:
  PlmnId m_PlmnId;

  std::vector<TacRange> m_TacRangeList;

  std::string m_Nid;
  bool m_NidIsSet;
};

}  // namespace model
}  // namespace nssf_server
}  // namespace oai

#endif /* TaiRange_H_ */
