/**
 * AUSF API
 * AUSF UE Authentication Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The OpenAirInterface Software Alliance licenses this file to You under
 * the OAI Public License, Version 1.1  (the "License"); you may not use this
 *file except in compliance with the License. You may obtain a copy of the
 *License at
 *
 *      http://www.openairinterface.org/?page_id=698
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *-------------------------------------------------------------------------------
 * For more information about the OpenAirInterface (OAI) Software Alliance:
 *      contact@openairinterface.org
 */

#include "DeregistrationInfo.h"

namespace oai {
namespace ausf_server {
namespace model {

DeregistrationInfo::DeregistrationInfo() {
  m_Supi = "";
}

DeregistrationInfo::~DeregistrationInfo() {}

void DeregistrationInfo::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json& j, const DeregistrationInfo& o) {
  j         = nlohmann::json();
  j["supi"] = o.m_Supi;
}

void from_json(const nlohmann::json& j, DeregistrationInfo& o) {
  j.at("supi").get_to(o.m_Supi);
}

std::string DeregistrationInfo::getSupi() const {
  return m_Supi;
}
void DeregistrationInfo::setSupi(std::string const& value) {
  m_Supi = value;
}

}  // namespace model
}  // namespace ausf_server
}  // namespace oai
