/**
 * AUSF API
 * AUSF UE Authentication Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The OpenAirInterface Software Alliance licenses this file to You under
 * the OAI Public License, Version 1.1  (the "License"); you may not use this
 *file except in compliance with the License. You may obtain a copy of the
 *License at
 *
 *      http://www.openairinterface.org/?page_id=698
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *-------------------------------------------------------------------------------
 * For more information about the OpenAirInterface (OAI) Software Alliance:
 *      contact@openairinterface.org
 */

/*
 * RgAuthCtx.h
 *
 *
 */

#ifndef RgAuthCtx_H_
#define RgAuthCtx_H_

#include <string>
#include "AuthResult.h"
#include <nlohmann/json.hpp>

namespace oai {
namespace ausf_server {
namespace model {

/// <summary>
///
/// </summary>
class RgAuthCtx {
 public:
  RgAuthCtx();
  virtual ~RgAuthCtx();

  void validate();

  /////////////////////////////////////////////
  /// RgAuthCtx members

  /// <summary>
  ///
  /// </summary>
  AuthResult getAuthResult() const;
  void setAuthResult(AuthResult const& value);
  /// <summary>
  ///
  /// </summary>
  std::string getSupi() const;
  void setSupi(std::string const& value);
  bool supiIsSet() const;
  void unsetSupi();
  /// <summary>
  ///
  /// </summary>
  bool isAuthInd() const;
  void setAuthInd(bool const value);
  bool authIndIsSet() const;
  void unsetAuthInd();

  friend void to_json(nlohmann::json& j, const RgAuthCtx& o);
  friend void from_json(const nlohmann::json& j, RgAuthCtx& o);

 protected:
  AuthResult m_AuthResult;

  std::string m_Supi;
  bool m_SupiIsSet;
  bool m_AuthInd;
  bool m_AuthIndIsSet;
};

}  // namespace model
}  // namespace ausf_server
}  // namespace oai

#endif /* RgAuthCtx_H_ */
