/**
 * Namf_EventExposure
 * AMF Event Exposure Service © 2019, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * AmfEventArea.h
 *
 *
 */

#ifndef AmfEventArea_H_
#define AmfEventArea_H_

#include "PresenceInfo.h"
#include "LadnInfo.h"
#include <nlohmann/json.hpp>

namespace oai::amf::model {

/// <summary>
///
/// </summary>
class AmfEventArea {
 public:
  AmfEventArea();
  virtual ~AmfEventArea() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  bool operator==(const AmfEventArea& rhs) const;
  bool operator!=(const AmfEventArea& rhs) const;

  /////////////////////////////////////////////
  /// AmfEventArea members

  /// <summary>
  ///
  /// </summary>
  PresenceInfo getPresenceInfo() const;
  void setPresenceInfo(PresenceInfo const& value);
  bool presenceInfoIsSet() const;
  void unsetPresenceInfo();
  /// <summary>
  ///
  /// </summary>
  LadnInfo getLadnInfo() const;
  void setLadnInfo(LadnInfo const& value);
  bool ladnInfoIsSet() const;
  void unsetLadnInfo();

  friend void to_json(nlohmann::json& j, const AmfEventArea& o);
  friend void from_json(const nlohmann::json& j, AmfEventArea& o);
  // Helper overload for validate. Used when one model stores another model and
  // calls it's validate.
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

 protected:
  PresenceInfo m_PresenceInfo;
  bool m_PresenceInfoIsSet;
  LadnInfo m_LadnInfo;
  bool m_LadnInfoIsSet;
};

}  // namespace oai::amf::model

#endif /* AmfEventArea_H_ */
