/**
 * Namf_EventExposure
 * AMF Event Exposure Service © 2019, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "LocationFilter.h"
#include "Helpers.h"

#include <sstream>

namespace oai::amf::model {

LocationFilter::LocationFilter() {}

void LocationFilter::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::amf::helpers::ValidationException(msg.str());
  }
}

bool LocationFilter::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool LocationFilter::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "LocationFilter" : pathPrefix;

  return success;
}

bool LocationFilter::operator==(const LocationFilter& rhs) const {
  return true;  // TODO

  ;
}

bool LocationFilter::operator!=(const LocationFilter& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const LocationFilter& o) {
  j = nlohmann::json();
}

void from_json(const nlohmann::json& j, LocationFilter& o) {}

}  // namespace oai::amf::model
