/*
 * Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The OpenAirInterface Software Alliance licenses this file to You under
 * the OAI Public License, Version 1.1  (the "License"); you may not use this
 * file except in compliance with the License. You may obtain a copy of the
 * License at
 *
 *      http://www.openairinterface.org/?page_id=698
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *-------------------------------------------------------------------------------
 * For more information about the OpenAirInterface (OAI) Software Alliance:
 *      contact@openairinterface.org
 */
/**
 * Nudm_SDM
 * Nudm Subscriber Data Management Service. � 2019, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "Arp.h"

namespace oai {
namespace udm {
namespace model {

Arp::Arp() {
  m_PriorityLevel = 0;
}

Arp::~Arp() {}

void Arp::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json& j, const Arp& o) {
  j                  = nlohmann::json();
  j["priorityLevel"] = o.m_PriorityLevel;
  j["preemptCap"]    = o.m_PreemptCap;
  j["preemptVuln"]   = o.m_PreemptVuln;
}

void from_json(const nlohmann::json& j, Arp& o) {
  j.at("priorityLevel").get_to(o.m_PriorityLevel);
  j.at("preemptCap").get_to(o.m_PreemptCap);
  j.at("preemptVuln").get_to(o.m_PreemptVuln);
}

int32_t Arp::getPriorityLevel() const {
  return m_PriorityLevel;
}
void Arp::setPriorityLevel(int32_t const value) {
  m_PriorityLevel = value;
}
PreemptionCapability Arp::getPreemptCap() const {
  return m_PreemptCap;
}
void Arp::setPreemptCap(PreemptionCapability const& value) {
  m_PreemptCap = value;
}
PreemptionVulnerability Arp::getPreemptVuln() const {
  return m_PreemptVuln;
}
void Arp::setPreemptVuln(PreemptionVulnerability const& value) {
  m_PreemptVuln = value;
}

}  // namespace model
}  // namespace udm
}  // namespace oai
