# mysql image version
## ref: https://hub.docker.com/r/library/mysql/tags/
##
image: "image-registry.openshift-image-registry.svc:5000/oaicicd-tmp/mysql-internal"
imageTag: "5.7.30"

strategy:
  type: Recreate

busybox:
  image: "image-registry.openshift-image-registry.svc:5000/oaicicd-5gcn-tmp/busybox-internal"
  tag: "latest"

testFramework:
  enabled: false
  image: "bats/bats"
  tag: "1.2.1"
  imagePullPolicy: IfNotPresent
  securityContext: {}

## Specify password for root user
##
## Default: random 10 character string
mysqlRootPassword: linux

## Create a database user
##
mysqlUser: test
## Default: random 10 character string
mysqlPassword: test

## Allow unauthenticated access, uncomment to enable
##
# mysqlAllowEmptyPassword: true

## Create a database
##
mysqlDatabase: oai_db

## Specify an imagePullPolicy (Required)
## It's recommended to change this to 'Always' if the image tag is 'latest'
## ref: http://kubernetes.io/docs/user-guide/images/#updating-images
##
imagePullPolicy: IfNotPresent

## Additionnal arguments that are passed to the MySQL container.
## For example use --default-authentication-plugin=mysql_native_password if older clients need to
## connect to a MySQL 8 instance.
args: []

extraVolumes: |
  # - name: extras
  #   emptyDir: {}
extraVolumeMounts: |
  # - name: extras
  #   mountPath: /usr/share/extras
  #   readOnly: true
extraInitContainers: |
  # - name: do-something
  #   image: busybox
  #   command: ['do', 'something']
## A string to add extra environment variables
# extraEnvVars: |
#   - name: EXTRA_VAR
#     value: "extra"

# Optionally specify an array of imagePullSecrets.
# Secrets must be manually created in the namespace.
# ref: https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod
# imagePullSecrets:
  # - name: myRegistryKeySecretName

## Node selector
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
nodeSelector:
  env: dev

## Affinity
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}

## Tolerations for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []

livenessProbe:
  initialDelaySeconds: 50
  periodSeconds: 15
  timeoutSeconds: 10
  successThreshold: 1
  failureThreshold: 3

readinessProbe:
  initialDelaySeconds: 15
  periodSeconds: 15
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

## Persist data to a persistent volume
persistence:
  enabled: true
  ## database data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  accessMode: ReadWriteOnce
  size: 8Gi
  annotations: {}

## Use an alternate scheduler, e.g. "stork".
## ref: https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/
##
# schedulerName:

## Security context
securityContext:
  enabled: false
  runAsUser: 999
  fsGroup: 999

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 256Mi
    cpu: 100m

# Custom mysql configuration files path
configurationFilesPath: /etc/mysql/conf.d/

# Custom mysql configuration files used to override default mysql settings
configurationFiles: {}
#  mysql.cnf: |-
#    [mysqld]
#    skip-name-resolve
#    ssl-ca=/ssl/ca.pem
#    ssl-cert=/ssl/server-cert.pem
#    ssl-key=/ssl/server-key.pem

# Custom mysql init SQL files used to initialize the database
initializationFiles:
  first-db.sql: |-
    -- phpMyAdmin SQL Dump
    -- version 5.1.0
    -- https://www.phpmyadmin.net/
    --
    -- Host: 172.16.200.10:3306
    -- Generation Time: Mar 22, 2021 at 10:31 AM
    -- Server version: 5.7.33
    -- PHP Version: 7.4.15

    SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
    START TRANSACTION;
    SET time_zone = "+00:00";


    /*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
    /*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
    /*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
    /*!40101 SET NAMES utf8mb4 */;

    --
    -- Database: `oai_db`
    --

    -- --------------------------------------------------------

    --
    -- Table structure for table `AccessAndMobilitySubscriptionData`
    --

    CREATE TABLE `AccessAndMobilitySubscriptionData` (
      `ueid` varchar(15) NOT NULL,
      `servingPlmnid` varchar(15) NOT NULL,
      `supportedFeatures` varchar(50) DEFAULT NULL,
      `gpsis` json DEFAULT NULL,
      `internalGroupIds` json DEFAULT NULL,
      `sharedVnGroupDataIds` json DEFAULT NULL,
      `subscribedUeAmbr` json DEFAULT NULL,
      `nssai` json DEFAULT NULL,
      `ratRestrictions` json DEFAULT NULL,
      `forbiddenAreas` json DEFAULT NULL,
      `serviceAreaRestriction` json DEFAULT NULL,
      `coreNetworkTypeRestrictions` json DEFAULT NULL,
      `rfspIndex` int(10) DEFAULT NULL,
      `subsRegTimer` int(10) DEFAULT NULL,
      `ueUsageType` int(10) DEFAULT NULL,
      `mpsPriority` tinyint(1) DEFAULT NULL,
      `mcsPriority` tinyint(1) DEFAULT NULL,
      `activeTime` int(10) DEFAULT NULL,
      `sorInfo` json DEFAULT NULL,
      `sorInfoExpectInd` tinyint(1) DEFAULT NULL,
      `sorafRetrieval` tinyint(1) DEFAULT NULL,
      `sorUpdateIndicatorList` json DEFAULT NULL,
      `upuInfo` json DEFAULT NULL,
      `micoAllowed` tinyint(1) DEFAULT NULL,
      `sharedAmDataIds` json DEFAULT NULL,
      `odbPacketServices` json DEFAULT NULL,
      `serviceGapTime` int(10) DEFAULT NULL,
      `mdtUserConsent` json DEFAULT NULL,
      `mdtConfiguration` json DEFAULT NULL,
      `traceData` json DEFAULT NULL,
      `cagData` json DEFAULT NULL,
      `stnSr` varchar(50) DEFAULT NULL,
      `cMsisdn` varchar(50) DEFAULT NULL,
      `nbIoTUePriority` int(10) DEFAULT NULL,
      `nssaiInclusionAllowed` tinyint(1) DEFAULT NULL,
      `rgWirelineCharacteristics` varchar(50) DEFAULT NULL,
      `ecRestrictionDataWb` json DEFAULT NULL,
      `ecRestrictionDataNb` tinyint(1) DEFAULT NULL,
      `expectedUeBehaviourList` json DEFAULT NULL,
      `primaryRatRestrictions` json DEFAULT NULL,
      `secondaryRatRestrictions` json DEFAULT NULL,
      `edrxParametersList` json DEFAULT NULL,
      `ptwParametersList` json DEFAULT NULL,
      `iabOperationAllowed` tinyint(1) DEFAULT NULL,
      `wirelineForbiddenAreas` json DEFAULT NULL,
      `wirelineServiceAreaRestriction` json DEFAULT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

    -- --------------------------------------------------------

    --
    -- Table structure for table `Amf3GppAccessRegistration`
    --

    CREATE TABLE `Amf3GppAccessRegistration` (
      `ueid` varchar(15) NOT NULL,
      `amfInstanceId` varchar(50) NOT NULL,
      `supportedFeatures` varchar(50) DEFAULT NULL,
      `purgeFlag` tinyint(1) DEFAULT NULL,
      `pei` varchar(50) DEFAULT NULL,
      `imsVoPs` json DEFAULT NULL,
      `deregCallbackUri` varchar(50) NOT NULL,
      `amfServiceNameDereg` json DEFAULT NULL,
      `pcscfRestorationCallbackUri` varchar(50) DEFAULT NULL,
      `amfServiceNamePcscfRest` json DEFAULT NULL,
      `initialRegistrationInd` tinyint(1) DEFAULT NULL,
      `guami` json NOT NULL,
      `backupAmfInfo` json DEFAULT NULL,
      `drFlag` tinyint(1) DEFAULT NULL,
      `ratType` json NOT NULL,
      `urrpIndicator` tinyint(1) DEFAULT NULL,
      `amfEeSubscriptionId` varchar(50) DEFAULT NULL,
      `epsInterworkingInfo` json DEFAULT NULL,
      `ueSrvccCapability` tinyint(1) DEFAULT NULL,
      `registrationTime` varchar(50) DEFAULT NULL,
      `vgmlcAddress` json DEFAULT NULL,
      `contextInfo` json DEFAULT NULL,
      `noEeSubscriptionInd` tinyint(1) DEFAULT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

    -- --------------------------------------------------------

    --
    -- Table structure for table `AuthenticationStatus`
    --

    CREATE TABLE `AuthenticationStatus` (
      `ueid` varchar(20) NOT NULL,
      `nfInstanceId` varchar(50) NOT NULL,
      `success` tinyint(1) NOT NULL,
      `timeStamp` varchar(50) NOT NULL,
      `authType` varchar(25) NOT NULL,
      `servingNetworkName` varchar(50) NOT NULL,
      `authRemovalInd` tinyint(1) DEFAULT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

    -- --------------------------------------------------------

    --
    -- Table structure for table `AuthenticationSubscription`
    --

    CREATE TABLE `AuthenticationSubscription` (
      `ueid` varchar(20) NOT NULL,
      `authenticationMethod` varchar(25) NOT NULL,
      `encPermanentKey` varchar(50) DEFAULT NULL,
      `protectionParameterId` varchar(50) DEFAULT NULL,
      `sequenceNumber` json DEFAULT NULL,
      `authenticationManagementField` varchar(50) DEFAULT NULL,
      `algorithmId` varchar(50) DEFAULT NULL,
      `encOpcKey` varchar(50) DEFAULT NULL,
      `encTopcKey` varchar(50) DEFAULT NULL,
      `vectorGenerationInHss` tinyint(1) DEFAULT NULL,
      `n5gcAuthMethod` varchar(15) DEFAULT NULL,
      `rgAuthenticationInd` tinyint(1) DEFAULT NULL,
      `supi` varchar(20) DEFAULT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

    --
    -- Dumping data for table `AuthenticationSubscription`
    --

    INSERT INTO `AuthenticationSubscription` (`ueid`, `authenticationMethod`, `encPermanentKey`, `protectionParameterId`, `sequenceNumber`, `authenticationManagementField`, `algorithmId`, `encOpcKey`, `encTopcKey`, `vectorGenerationInHss`, `n5gcAuthMethod`, `rgAuthenticationInd`, `supi`) VALUES
    ('208950000000031', '5G_AKA', '0C0A34601D4F07677303652C0462535B', '0C0A34601D4F07677303652C0462535B', '{\"sqn\": \"000000000020\", \"sqnScheme\": \"NON_TIME_BASED\", \"lastIndexes\": {\"ausf\": 0}}', '8000', 'milenage', '63bfa50ee6523365ff14c1f45f88737d', NULL, NULL, NULL, NULL, '208950000000031');

    -- --------------------------------------------------------

    --
    -- Table structure for table `SdmSubscriptions`
    --

    CREATE TABLE `SdmSubscriptions` (
      `ueid` varchar(15) NOT NULL,
      `subsId` int(10) UNSIGNED NOT NULL,
      `nfInstanceId` varchar(50) NOT NULL,
      `implicitUnsubscribe` tinyint(1) DEFAULT NULL,
      `expires` varchar(50) DEFAULT NULL,
      `callbackReference` varchar(50) NOT NULL,
      `amfServiceName` json DEFAULT NULL,
      `monitoredResourceUris` json NOT NULL,
      `singleNssai` json DEFAULT NULL,
      `dnn` varchar(50) DEFAULT NULL,
      `subscriptionId` varchar(50) DEFAULT NULL,
      `plmnId` json DEFAULT NULL,
      `immediateReport` tinyint(1) DEFAULT NULL,
      `report` json DEFAULT NULL,
      `supportedFeatures` varchar(50) DEFAULT NULL,
      `contextInfo` json DEFAULT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

    -- --------------------------------------------------------

    --
    -- Table structure for table `SessionManagementSubscriptionData`
    --

    CREATE TABLE `SessionManagementSubscriptionData` (
      `ueid` varchar(15) NOT NULL,
      `servingPlmnid` varchar(15) NOT NULL,
      `singleNssai` json NOT NULL,
      `dnnConfigurations` json DEFAULT NULL,
      `internalGroupIds` json DEFAULT NULL,
      `sharedVnGroupDataIds` json DEFAULT NULL,
      `sharedDnnConfigurationsId` varchar(50) DEFAULT NULL,
      `odbPacketServices` json DEFAULT NULL,
      `traceData` json DEFAULT NULL,
      `sharedTraceDataId` varchar(50) DEFAULT NULL,
      `expectedUeBehavioursList` json DEFAULT NULL,
      `suggestedPacketNumDlList` json DEFAULT NULL,
      `3gppChargingCharacteristics` varchar(50) DEFAULT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

    -- --------------------------------------------------------

    --
    -- Table structure for table `SmfRegistrations`
    --

    CREATE TABLE `SmfRegistrations` (
      `ueid` varchar(15) NOT NULL,
      `subpduSessionId` int(10) NOT NULL,
      `smfInstanceId` varchar(50) NOT NULL,
      `smfSetId` varchar(50) DEFAULT NULL,
      `supportedFeatures` varchar(50) DEFAULT NULL,
      `pduSessionId` int(10) NOT NULL,
      `singleNssai` json NOT NULL,
      `dnn` varchar(50) DEFAULT NULL,
      `emergencyServices` tinyint(1) DEFAULT NULL,
      `pcscfRestorationCallbackUri` varchar(50) DEFAULT NULL,
      `plmnId` json NOT NULL,
      `pgwFqdn` varchar(50) DEFAULT NULL,
      `epdgInd` tinyint(1) DEFAULT NULL,
      `deregCallbackUri` varchar(50) DEFAULT NULL,
      `registrationReason` json DEFAULT NULL,
      `registrationTime` varchar(50) DEFAULT NULL,
      `contextInfo` json DEFAULT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

    -- --------------------------------------------------------

    --
    -- Table structure for table `SmfSelectionSubscriptionData`
    --

    CREATE TABLE `SmfSelectionSubscriptionData` (
      `ueid` varchar(15) NOT NULL,
      `servingPlmnid` varchar(15) NOT NULL,
      `supportedFeatures` varchar(50) DEFAULT NULL,
      `subscribedSnssaiInfos` json DEFAULT NULL,
      `sharedSnssaiInfosId` varchar(50) DEFAULT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

    --
    -- Indexes for dumped tables
    --

    --
    -- Indexes for table `AccessAndMobilitySubscriptionData`
    --
    ALTER TABLE `AccessAndMobilitySubscriptionData`
      ADD PRIMARY KEY (`ueid`,`servingPlmnid`) USING BTREE;

    --
    -- Indexes for table `Amf3GppAccessRegistration`
    --
    ALTER TABLE `Amf3GppAccessRegistration`
      ADD PRIMARY KEY (`ueid`);

    --
    -- Indexes for table `AuthenticationStatus`
    --
    ALTER TABLE `AuthenticationStatus`
      ADD PRIMARY KEY (`ueid`);

    --
    -- Indexes for table `AuthenticationSubscription`
    --
    ALTER TABLE `AuthenticationSubscription`
      ADD PRIMARY KEY (`ueid`);

    --
    -- Indexes for table `SdmSubscriptions`
    --
    ALTER TABLE `SdmSubscriptions`
      ADD PRIMARY KEY (`subsId`,`ueid`) USING BTREE;

    --
    -- Indexes for table `SessionManagementSubscriptionData`
    --
    ALTER TABLE `SessionManagementSubscriptionData`
      ADD PRIMARY KEY (`ueid`,`servingPlmnid`) USING BTREE;

    --
    -- Indexes for table `SmfRegistrations`
    --
    ALTER TABLE `SmfRegistrations`
      ADD PRIMARY KEY (`ueid`,`subpduSessionId`) USING BTREE;

    --
    -- Indexes for table `SmfSelectionSubscriptionData`
    --
    ALTER TABLE `SmfSelectionSubscriptionData`
      ADD PRIMARY KEY (`ueid`,`servingPlmnid`) USING BTREE;

    --
    -- AUTO_INCREMENT for dumped tables
    --

    --
    -- AUTO_INCREMENT for table `SdmSubscriptions`
    --
    ALTER TABLE `SdmSubscriptions`
      MODIFY `subsId` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;
    COMMIT;

    /*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
    /*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
    /*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;

#  second-db.sql: |-
#    CREATE DATABASE IF NOT EXISTS second DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;

# To enaable the mysql X Protocol's port
# .. will expose the port 33060
# .. Note the X Plugin needs installation
# ref: https://dev.mysql.com/doc/refman/8.0/en/x-plugin-checking-installation.html
mysqlx:
  port:
    enabled: false

metrics:
  enabled: false
  image: prom/mysqld-exporter
  imageTag: v0.10.0
  imagePullPolicy: IfNotPresent
  resources: {}
  annotations: {}
    # prometheus.io/scrape: "true"
    # prometheus.io/port: "9104"
  livenessProbe:
    initialDelaySeconds: 15
    timeoutSeconds: 5
  readinessProbe:
    initialDelaySeconds: 5
    timeoutSeconds: 1
  flags: []
  serviceMonitor:
    enabled: false
    additionalLabels: {}

## Configure the service
## ref: http://kubernetes.io/docs/user-guide/services/
service:
  annotations: {}
  ## Specify a service type
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services---service-types
  type: ClusterIP
  port: 3306
  # nodePort: 32000
  # loadBalancerIP:

## Pods Service Account
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
serviceAccount:
  ## Specifies whether a ServiceAccount should be created
  ##
  create: false
  ## The name of the ServiceAccount to use.
  ## If not set and create is true, a name is generated using the mariadb.fullname template
  # name:

ssl:
  enabled: false
  secret: mysql-ssl-certs
  certificates:
#  - name: mysql-ssl-certs
#    ca: |-
#      -----BEGIN CERTIFICATE-----
#      ...
#      -----END CERTIFICATE-----
#    cert: |-
#      -----BEGIN CERTIFICATE-----
#      ...
#      -----END CERTIFICATE-----
#    key: |-
#      -----BEGIN RSA PRIVATE KEY-----
#      ...
#      -----END RSA PRIVATE KEY-----

## Populates the 'TZ' system timezone environment variable
## ref: https://dev.mysql.com/doc/refman/5.7/en/time-zone-support.html
##
## Default: nil (mysql will use image's default timezone, normally UTC)
## Example: 'Australia/Sydney'
# timezone:

# Deployment Annotations
deploymentAnnotations: {}

# To be added to the database server pod(s)
podAnnotations: {}
podLabels: {}

## Set pod priorityClassName
# priorityClassName: {}


## Init container resources defaults
initContainer:
  resources:
    requests:
      memory: 10Mi
      cpu: 10m
