/*
 * Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The OpenAirInterface Software Alliance licenses this file to You under
 * the OAI Public License, Version 1.1  (the "License"); you may not use this
 * file except in compliance with the License. You may obtain a copy of the
 * License at
 *
 *      http://www.openairinterface.org/?page_id=698
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *-------------------------------------------------------------------------------
 * For more information about the OpenAirInterface (OAI) Software Alliance:
 *      contact@openairinterface.org
 */
/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "GeographicArea.h"

namespace oai::udr::model {

GeographicArea::GeographicArea() {
  m_Uncertainty = 0.0f;
  m_Confidence = 0;
  m_Altitude = 0.0;
  m_UncertaintyAltitude = 0.0f;
  m_InnerRadius = 0;
  m_UncertaintyRadius = 0.0f;
  m_OffsetAngle = 0;
  m_IncludedAngle = 0;
}

GeographicArea::~GeographicArea() {}

void GeographicArea::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json &j, const GeographicArea &o) {
  j = nlohmann::json();
  j["shape"] = o.m_Shape;
  j["point"] = o.m_Point;
  j["uncertainty"] = o.m_Uncertainty;
  j["uncertaintyEllipse"] = o.m_UncertaintyEllipse;
  j["confidence"] = o.m_Confidence;
  j["pointList"] = o.m_PointList;
  j["altitude"] = o.m_Altitude;
  j["uncertaintyAltitude"] = o.m_UncertaintyAltitude;
  j["innerRadius"] = o.m_InnerRadius;
  j["uncertaintyRadius"] = o.m_UncertaintyRadius;
  j["offsetAngle"] = o.m_OffsetAngle;
  j["includedAngle"] = o.m_IncludedAngle;
}

void from_json(const nlohmann::json &j, GeographicArea &o) {
  j.at("shape").get_to(o.m_Shape);
  j.at("point").get_to(o.m_Point);
  j.at("uncertainty").get_to(o.m_Uncertainty);
  j.at("uncertaintyEllipse").get_to(o.m_UncertaintyEllipse);
  j.at("confidence").get_to(o.m_Confidence);
  j.at("pointList").get_to(o.m_PointList);
  j.at("altitude").get_to(o.m_Altitude);
  j.at("uncertaintyAltitude").get_to(o.m_UncertaintyAltitude);
  j.at("innerRadius").get_to(o.m_InnerRadius);
  j.at("uncertaintyRadius").get_to(o.m_UncertaintyRadius);
  j.at("offsetAngle").get_to(o.m_OffsetAngle);
  j.at("includedAngle").get_to(o.m_IncludedAngle);
}

SupportedGADShapes GeographicArea::getShape() const { return m_Shape; }
void GeographicArea::setShape(SupportedGADShapes const &value) {
  m_Shape = value;
}
GeographicalCoordinates GeographicArea::getPoint() const { return m_Point; }
void GeographicArea::setPoint(GeographicalCoordinates const &value) {
  m_Point = value;
}
float GeographicArea::getUncertainty() const { return m_Uncertainty; }
void GeographicArea::setUncertainty(float const value) {
  m_Uncertainty = value;
}
UncertaintyEllipse GeographicArea::getUncertaintyEllipse() const {
  return m_UncertaintyEllipse;
}
void GeographicArea::setUncertaintyEllipse(UncertaintyEllipse const &value) {
  m_UncertaintyEllipse = value;
}
int32_t GeographicArea::getConfidence() const { return m_Confidence; }
void GeographicArea::setConfidence(int32_t const value) {
  m_Confidence = value;
}
std::vector<GeographicalCoordinates> &GeographicArea::getPointList() {
  return m_PointList;
}
void GeographicArea::setPointList(
    std::vector<GeographicalCoordinates> const &value) {
  m_PointList = value;
}
double GeographicArea::getAltitude() const { return m_Altitude; }
void GeographicArea::setAltitude(double const value) { m_Altitude = value; }
float GeographicArea::getUncertaintyAltitude() const {
  return m_UncertaintyAltitude;
}
void GeographicArea::setUncertaintyAltitude(float const value) {
  m_UncertaintyAltitude = value;
}
int32_t GeographicArea::getInnerRadius() const { return m_InnerRadius; }
void GeographicArea::setInnerRadius(int32_t const value) {
  m_InnerRadius = value;
}
float GeographicArea::getUncertaintyRadius() const {
  return m_UncertaintyRadius;
}
void GeographicArea::setUncertaintyRadius(float const value) {
  m_UncertaintyRadius = value;
}
int32_t GeographicArea::getOffsetAngle() const { return m_OffsetAngle; }
void GeographicArea::setOffsetAngle(int32_t const value) {
  m_OffsetAngle = value;
}
int32_t GeographicArea::getIncludedAngle() const { return m_IncludedAngle; }
void GeographicArea::setIncludedAngle(int32_t const value) {
  m_IncludedAngle = value;
}

} // namespace oai::udr::model
