/*
 * Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The OpenAirInterface Software Alliance licenses this file to You under
 * the OAI Public License, Version 1.1  (the "License"); you may not use this
 * file except in compliance with the License. You may obtain a copy of the
 * License at
 *
 *      http://www.openairinterface.org/?page_id=698
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *-------------------------------------------------------------------------------
 * For more information about the OpenAirInterface (OAI) Software Alliance:
 *      contact@openairinterface.org
 */
/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "IptvConfigDataPatch.h"

namespace oai::udr::model {

IptvConfigDataPatch::IptvConfigDataPatch() { m_MultiAccCtrlsIsSet = false; }

IptvConfigDataPatch::~IptvConfigDataPatch() {}

void IptvConfigDataPatch::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json &j, const IptvConfigDataPatch &o) {
  j = nlohmann::json();
  if (o.multiAccCtrlsIsSet() || !o.m_MultiAccCtrls.empty())
    j["multiAccCtrls"] = o.m_MultiAccCtrls;
}

void from_json(const nlohmann::json &j, IptvConfigDataPatch &o) {
  if (j.find("multiAccCtrls") != j.end()) {
    j.at("multiAccCtrls").get_to(o.m_MultiAccCtrls);
    o.m_MultiAccCtrlsIsSet = true;
  }
}

std::map<std::string, MulticastAccessControl> &
IptvConfigDataPatch::getMultiAccCtrls() {
  return m_MultiAccCtrls;
}
void IptvConfigDataPatch::setMultiAccCtrls(
    std::map<std::string, MulticastAccessControl> const &value) {
  m_MultiAccCtrls = value;
  m_MultiAccCtrlsIsSet = true;
}
bool IptvConfigDataPatch::multiAccCtrlsIsSet() const {
  return m_MultiAccCtrlsIsSet;
}
void IptvConfigDataPatch::unsetMultiAccCtrls() { m_MultiAccCtrlsIsSet = false; }

} // namespace oai::udr::model
