/*
 * Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The OpenAirInterface Software Alliance licenses this file to You under
 * the OAI Public License, Version 1.1  (the "License"); you may not use this
 * file except in compliance with the License. You may obtain a copy of the
 * License at
 *
 *      http://www.openairinterface.org/?page_id=698
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *-------------------------------------------------------------------------------
 * For more information about the OpenAirInterface (OAI) Software Alliance:
 *      contact@openairinterface.org
 */
/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "OdbData.h"

namespace oai::udr::model {

OdbData::OdbData() { m_RoamingOdbIsSet = false; }

OdbData::~OdbData() {}

void OdbData::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json &j, const OdbData &o) {
  j = nlohmann::json();
  if (o.roamingOdbIsSet())
    j["roamingOdb"] = o.m_RoamingOdb;
}

void from_json(const nlohmann::json &j, OdbData &o) {
  if (j.find("roamingOdb") != j.end()) {
    j.at("roamingOdb").get_to(o.m_RoamingOdb);
    o.m_RoamingOdbIsSet = true;
  }
}

RoamingOdb OdbData::getRoamingOdb() const { return m_RoamingOdb; }
void OdbData::setRoamingOdb(RoamingOdb const &value) {
  m_RoamingOdb = value;
  m_RoamingOdbIsSet = true;
}
bool OdbData::roamingOdbIsSet() const { return m_RoamingOdbIsSet; }
void OdbData::unsetRoamingOdb() { m_RoamingOdbIsSet = false; }

} // namespace oai::udr::model
