/*
 * Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The OpenAirInterface Software Alliance licenses this file to You under
 * the OAI Public License, Version 1.1  (the "License"); you may not use this
 * file except in compliance with the License. You may obtain a copy of the
 * License at
 *
 *      http://www.openairinterface.org/?page_id=698
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *-------------------------------------------------------------------------------
 * For more information about the OpenAirInterface (OAI) Software Alliance:
 *      contact@openairinterface.org
 */
/**
 * Nudm_EE
 * Nudm Event Exposure Service. © 2021, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * CreateEESubscriptionApiImpl.h
 *
 *
 */

#ifndef CREATE_EE_SUBSCRIPTION_API_IMPL_H_
#define CREATE_EE_SUBSCRIPTION_API_IMPL_H_

#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>
#include <optional>
#include <string>
#include <CreateEESubscriptionApi.h>

#include "CreatedEeSubscription.h"
#include "EeSubscription.h"
#include "ProblemDetails.h"
#include "udm_app.hpp"

namespace oai::udm::api {

using namespace oai::udm::model;
using namespace oai::udm::app;

class CreateEESubscriptionApiImpl
    : public oai::udm::api::CreateEESubscriptionApi {
 public:
  explicit CreateEESubscriptionApiImpl(
      const std::shared_ptr<Pistache::Rest::Router>& rtr, udm_app* udm_app_inst,
      std::string address);
  ~CreateEESubscriptionApiImpl() override = default;

  void create_ee_subscription(
      const std::string& ueIdentity, const EeSubscription& eeSubscription,
      Pistache::Http::ResponseWriter& response);

 private:
  udm_app* m_udm_app;
  std::string m_address;
};

}  // namespace oai::udm::api

#endif
