/**
 * NSSF NSSAI Availability
 * NSSF NSSAI Availability Service. © 2021, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * NssfSliceConfigApiImpl.h
 *
 *
 */

#ifndef NSSF_SLICE_CONFIG_API_IMPL_H
#define NSSF_SLICE_CONFIG_API_IMPL_H

#include <memory>
#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>

#include <NssfSliceConfigApi.h>

#include <pistache/optional.h>

#include "PatchItem.h"
#include "ProblemDetails.h"
#include "RedirectResponse.h"
#include "nssf_app.hpp"

#include <string>
#include <vector>

namespace oai {
namespace nssf_server {
namespace api {

using namespace oai::nssf_server::model;
using namespace nssf;

class NssfSliceConfigApiImpl
    : public oai::nssf_server::api::NssfSliceConfigApi {
 public:
  NssfSliceConfigApiImpl(
      std::shared_ptr<Pistache::Rest::Router>, nssf_app* nssf_app_inst,
      std::string address);
  ~NssfSliceConfigApiImpl() {}

  void nssf_slice_config_get_apis(Pistache::Http::ResponseWriter& response);
  void nssf_slice_config_get(Pistache::Http::ResponseWriter& response);

 private:
  nssf_app* m_nssf_app;
  std::string m_address;
};

}  // namespace api
}  // namespace nssf_server
}  // namespace oai

#endif
