/**
 * NSSF NSSAI Availability
 * NSSF NSSAI Availability Service. © 2021, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "SubscriptionsCollectionApiImpl.h"
#include "Helpers.h"

namespace oai {
namespace nssf_server {
namespace api {

using namespace oai::nssf_server::helpers;
using namespace oai::nssf_server::model;
using namespace nssf;

// SubscriptionsCollectionApiImpl::SubscriptionsCollectionApiImpl(const
// std::shared_ptr<Pistache::Rest::Router>& rtr)
//     : SubscriptionsCollectionApi(rtr)
// {
// }

SubscriptionsCollectionApiImpl::SubscriptionsCollectionApiImpl(
    std::shared_ptr<Pistache::Rest::Router> rtr, nssf_app* nssf_app_inst,
    std::string address)
    : SubscriptionsCollectionApi(rtr),
      m_nssf_app(nssf_app_inst),
      m_address(address) {}

void SubscriptionsCollectionApiImpl::n_ssai_availability_post(
    const NssfEventSubscriptionCreateData& nssfEventSubscriptionCreateData,
    const Pistache::Optional<Pistache::Http::Header::Raw>& contentEncoding,
    Pistache::Http::ResponseWriter& response) {
  response.send(
      Pistache::Http::Code::Service_Unavailable, "API NOT IMPLEMENTED\n");
}

}  // namespace api
}  // namespace nssf_server
}  // namespace oai
